In [4]:

#%matplotlib inline
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from lightfm import LightFM
from nltk.corpus import stopwords
import random

item_dataset=pd.read_csv('itemWm.csv')

/Users/a0s00x0/opt/anaconda3/lib/python3.7/site-packages/lightfm/_lightfm_fast.py:10: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  "LightFM was compiled without OpenMP support. "

In [2]:
item_dataset.head(3)

,Product ID,Item ID,WUPC,GTIN,Product Class Type,Pub Status,Avail. Status,Payload,Brand Name,Name,Category,Tax Code,Ceiling Price,Abstract Product Id,Attrs. Quality Score
0,0RDB0HT17AGU,112270954,NaN,15213731528,REGULAR,UNPUBLISHED,NaN,NaN,365 Kids From Garanimals,365 Kids 8pcpoplin Shirt,Shirts & Tops,NaN,NaN,NaN,0.081
1,0REBFYPCW4P4,35522059,7.102978e+10,710297822147,REGULAR,UNPUBLISHED,NOT_AVAILABLE,NaN,White Stag,White Stag Women's Short Sleeve V Neck L,Clothing,NaN,1300.0,NaN,0.531
2,0RFDTVHHPXK9,825559729,NaN,716398039224,REGULAR,UNPUBLISHED,NaN,NaN,Iceburg,24pciceburg Jacket,Clothing,NaN,NaN,NaN,0.000

In [3]:
#Data Preprocessing 
#Get tags from Item dataset
Tag=[]
Tags={}
Rating={}
for num in range(0,len(item_dataset)):
    key=item_dataset.iloc[num]['Item ID']
    name=item_dataset.iloc[num]['Name']
    nameToTags = ','.join([word for word in name.split() if word not in stopwords.words("english")])
    value=nameToTags.split(',')
    Tags[key]=value
    Tag.append(value)
    rating = random.randint(1, 5)
    Rating[key]=rating

NameError: name 'item_dataset' is not defined

In [7]:

item_dataset.head(3)

,Product ID,Item ID,WUPC,GTIN,Product Class Type,Pub Status,Avail. Status,Payload,Brand Name,Name,Category,Tax Code,Ceiling Price,Abstract Product Id,Attrs. Quality Score
0,0RDB0HT17AGU,112270954,NaN,15213731528,REGULAR,UNPUBLISHED,NaN,NaN,365 Kids From Garanimals,365 Kids 8pcpoplin Shirt,Shirts & Tops,NaN,NaN,NaN,0.081
1,0REBFYPCW4P4,35522059,7.102978e+10,710297822147,REGULAR,UNPUBLISHED,NOT_AVAILABLE,NaN,White Stag,White Stag Women's Short Sleeve V Neck L,Clothing,NaN,1300.0,NaN,0.531
2,0RFDTVHHPXK9,825559729,NaN,716398039224,REGULAR,UNPUBLISHED,NaN,NaN,Iceburg,24pciceburg Jacket,Clothing,NaN,NaN,NaN,0.000

In [6]:

item_dataset['rating'].apply(pd.ceil)

KeyError: 'rating'

In [23]:



item_dataset = item_dataset.sort_values('rating', ascending=False).head(5)
item_dataset.head(3)

,Product ID,Item ID,WUPC,GTIN,Product Class Type,Pub Status,Avail. Status,Payload,Brand Name,Name,Category,Tax Code,Ceiling Price,Abstract Product Id,Attrs. Quality Score,tagArray,rating
0,0RDB0HT17AGU,112270954,NaN,15213731528,REGULAR,UNPUBLISHED,NaN,NaN,365 Kids From Garanimals,365 Kids 8pcpoplin Shirt,Shirts & Tops,NaN,NaN,NaN,0.081,"[365, Kids, 8pcpoplin, Shirt]",1
329,11GI2EOHQO7N,856657527,NaN,405830697718,REGULAR,UNPUBLISHED,NaN,NaN,NaN,24pcgeorge Flannel,Pants & Shorts,NaN,NaN,NaN,0.000,"[24pcgeorge, Flannel]",1
342,11SB96QYSRKO,957703865,NaN,889621672601,REGULAR,UNPUBLISHED,NaN,NaN,Florida State Seminoles,Florida State Blazer Knit,Clothing Accessories,NaN,1500.0,NaN,0.207,"[Florida, State, Blazer, Knit]",1

In [24]:

s = item_dataset.apply(lambda x: pd.Series(x['tagArray']),axis=1).stack().reset_index(level=1, drop=True)
s.name = 'tag'
gen_item_dataset = item_dataset.drop('tagArray', axis=1).join(s)


location_dataset=pd.read_csv('locationtags.csv')
location_dataset.head(5)

   locId          city                                               tags
0      1      New York  ['winters', 'woolen', 'wool', 'cold', 'sweater...
1      2   Los Angeles  ['summer', 'sunglasses', 'sun', 'cotton', 'sun...
2      3       Chicago  ['winters', 'woolen', 'wool', 'cold', 'sweaters']
3      4       Houston  ['Long', 'Long sleeves', 'denim', 'lightweight...
4      5  Philadelphia  ['winters', 'woolen', 'wool', 'cold', 'sweater...

In [18]:
#Converting the format of Genre column to a list and then appending to the new list
Tag=[]
Tags={}
for num in range(0,len(location_dataset)):
    key=location_dataset.iloc[num]['locId']
    value=location_dataset.iloc[num]['tags'].split(',')
    Tags[key]=value
    Tag.append(value)

In [20]:




       
location_dataset['tagArray']=Tag

#print(location_dataset.head(5))


def get_tags_from_location(location):
    df = location_dataset[location_dataset['city']==location]
    return df['tagArray']

In [ ]:

def build_chart(location, percentile=0.85):
    tagArray=get_tags_from_location(location)
    tagArray = list(tagArray)
    result=pd.DataFrame() 
    for tag in tagArray[0]:
        qualified=gen_item_dataset[gen_item_dataset['tag'] == tag]
        qualified=qualified.sort_values('rating',ascending=False).head(5)
        result = result.append(qualified[['itemNbr','itemDesc','brand','price','rating']].drop_duplicates()).drop_duplicates()
        
    result=result.sort_values('rating',ascending=False).head(5)
    return result


purchase_dataset=pd.read_csv('/Users/a0g00e6/Downloads/purchase.csv')
#purchase_dataset=purchase_dataset[purchase_dataset.itemNbr.isin(items['itemNbr'].to_list())]
        
user_item_purchase = pd.pivot_table(purchase_dataset, index='userId', columns='itemNbr', values='rating')

# fill missing values with 0
user_item_purchase = user_item_purchase.fillna(0)

user_item_purchase.head(10)

# convert to csr matrix
user_item_purchase_csr = csr_matrix(user_item_purchase.values)
user_item_purchase_csr

user_id = list(user_item_purchase.index)
user_dict = {}
counter = 0 
for i in user_id:
    user_dict[i] = counter
    counter += 1




model = LightFM(loss='warp',
                random_state=2016,
                learning_rate=0.90,
                no_components=150,
                user_alpha=0.000005)

model = model.fit(user_item_purchase_csr,
                  epochs=100,
                  num_threads=16, verbose=False)

In [ ]:
def sample_recommendation_user(model, user_item_purchase, user_id, user_dict,location, threshold = 0,nrec_items = 5, show = True):
    items=build_chart(location)
    item_dict ={}
    df = items[['itemNbr','itemDesc']].sort_values('itemDesc', ascending=False).reset_index()

    for i in range(df.shape[0]):
        item_dict[(df.loc[i,'itemNbr'])] = df.loc[i,'itemDesc']
    
    items=items[['itemNbr','rating']]
        
    items_selected_transformed = pd.get_dummies(items, columns = ['rating'])
    items_selected_transformed = items_selected_transformed.sort_values('itemNbr').reset_index().drop('index', axis=1)
    items_csr = csr_matrix(items_selected_transformed.drop('itemNbr', axis=1).values)

    user_item_purchase=user_item_purchase.loc[:,user_item_purchase.columns.isin(items['itemNbr'].to_list())]

    n_users, n_items = user_item_purchase.shape
    user_x = user_dict[user_id]
    scores = pd.Series(model.predict(user_x,np.arange(n_items), item_features=items_csr))
    scores.index = user_item_purchase.columns
    scores = list(pd.Series(scores.sort_values(ascending=False).index))
    known_items = list(pd.Series(user_item_purchase.loc[user_id,:] \
                                 [user_item_purchase.loc[user_id,:] > threshold].index).sort_values(ascending=False))
    scores = [x for x in scores if x not in known_items]
    return_score_list = scores[0:nrec_items]
    known_items = list(pd.Series(known_items).apply(lambda x: item_dict[x]))
    scores = list(pd.Series(scores).apply(lambda x: item_dict[x]))
    print(scores)


sample_recommendation_user(model, user_item_purchase, 'a124', user_dict, 'Ladakh')

def recommend(userId, location, model):
    result = pd.DataFrame()

    return result